### ISSUE TITLE
can i learn how to change stage 

### ISSUE THREAD

**Issue by THOBY555** [Blantados/BETADCIU-Source-Code#6]
im a big fan i just want to learn how u change the stage mid-fight on ur covers 

lol idnoo nothing at GitHub im new

**Comment by teotm** [comment]
Look at `modchart.lua` files.

**Comment by THOBY555** [comment]
> Look at `modchart.lua` files.

Oh wait that's me on the feature I just know how to do that from like a month and I just opened GitHub righ now
